### ISSUE TITLE
Speedscope viewing fails in development

### ISSUE THREAD

**Issue by spike01** [Shopify/app_profiler#15]
Added `app_profiler` to an app, tried to profile something locally:

```
yarn add v1.13.0
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
2020-07-06 18:34:36 -0400: Rack app error handling request { GET / }
#<AppProfiler::Viewer::SpeedscopeViewer::YarnError: Failed to run add --dev speedscope.>
/Users/spike/.gem/ruby/2.7.1/gems/app_profiler-0.0.5/lib/app_profiler/viewer/speedscope_viewer.rb:29:in `block in yarn'
/Users/spike/.gem/ruby/2.7.1/gems/app_profiler-0.0.5/lib/app_profiler/viewer/speedscope_viewer.rb:58:in `block in exec'
/Users/spike/.gem/ruby/2.7.1/gems/app_profiler-0.0.5/lib/app_profiler/viewer/speedscope_viewer.rb:57:in `tap'
/Users/spike/.gem/ruby/2.7.1/gems/app_profiler-0.0.5/lib/app_profiler/viewer/speedscope_viewer.rb:57:in `exec'
/Users/spike/.gem/ruby/2.7.1/gems/app_profiler-0.0.5/lib/app_profiler/viewer/speedscope_viewer.rb:28:in `yarn'
/Users/spike/.gem/ruby/2.7.1/gems/app_profiler-0.0.5/lib/app_profiler/viewer/speedscope_viewer.rb:36:in `setup_yarn'
/Users/spike/.gem/ruby/2.7.1/gems/app_profiler-0.0.5/lib/app_profiler/viewer/speedscope_viewer.rb:27:in `yarn'
/Users/spike/.gem/ruby/2.7.1/gems/app_profiler-0.0.5/lib/app_profiler/viewer/speedscope_viewer.rb:21:in `view'
/Users/spike/.gem/ruby/2.7.1/gems/app_profiler-0.0.5/lib/app_profiler/viewer/speedscope_viewer.rb:12:in `view'
/Users/spike/.gem/ruby/2.7.1/gems/app_profiler-0.0.5/lib/app_profiler/profile.rb:36:in `view'
/Users/spike/.gem/ruby/2.7.1/gems/app_profiler-0.0.5/lib/app_profiler/middleware/view_action.rb:8:in `call'
/Users/spike/.gem/ruby/2.7.1/gems/app_profiler-0.0.5/lib/app_profiler/middleware.rb:41:in `profile'
/Users/spike/.gem/ruby/2.7.1/gems/app_profiler-0.0.5/lib/app_profiler/middleware.rb:18:in `call'
/Users/spike/.gem/ruby/2.7.1/gems/railties-6.0.3.2/lib/rails/engine.rb:527:in `call'
/Users/spike/.gem/ruby/2.7.1/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
/Users/spike/.gem/ruby/2.7.1/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
/Users/spike/.gem/ruby/2.7.1/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
/Users/spike/.gem/ruby/2.7.1/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
/Users/spike/.gem/ruby/2.7.1/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

I've opened a PR (#16) that I think fixes it, but opening this issue in case the PR isn't the right way to fix it.

**Comment by imjching** [comment]
I managed to reproduce this error locally. See commits in https://github.com/imjching/app_profiler_demo.

This issue only occurs when a project uses Yarn Workspaces (https://classic.yarnpkg.com/blog/2017/08/02/introducing-workspaces/), i.e. allowing multiple `package.json` files in a single repository. Here's what the flag actually does:

```
 -W, --ignore-workspace-root-check   required to run yarn add inside a workspace root
```

I'm not very familiar with Yarn Workspaces, but it seems to me that whenever we use this feature, the `-W` flag (or its equivalence) is always needed to run `yarn add` for a workspace root. With that said, the PR that you have should fix the root cause. However, this implicitly makes an assumption in which we only support this gem in the base Gemfile. 

If we're adding the gem to an in-repo gem (think of "workspaces", but for Ruby), then this isn't right as we are now adding the dependency to the root's `package.json` instead of the gem's `package.json`. If that particular in-repo gem is extracted from the repository, its own `package.json` won't have the right dependencies. If that is actually the case, I would recommend creating a custom viewer for that as I don't see an easy way of fixing this unless we add an option to the gem to signify whether the gem is used as an in-repo gem. If that option is specified, we will run `yarn workspace <workspace name> add` instead of the regular `yarn add`.
